/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LokaleOversigtImport } from './routes/LokaleOversigt'
import { Route as LoginImport } from './routes/Login'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const LokaleOversigtRoute = LokaleOversigtImport.update({
  id: '/LokaleOversigt',
  path: '/LokaleOversigt',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/LokaleOversigt': {
      id: '/LokaleOversigt'
      path: '/LokaleOversigt'
      fullPath: '/LokaleOversigt'
      preLoaderRoute: typeof LokaleOversigtImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/Login': typeof LoginRoute
  '/LokaleOversigt': typeof LokaleOversigtRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRoutesByTo {
  '/Login': typeof LoginRoute
  '/LokaleOversigt': typeof LokaleOversigtRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/Login': typeof LoginRoute
  '/LokaleOversigt': typeof LokaleOversigtRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Login' | '/LokaleOversigt' | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/Login' | '/LokaleOversigt' | '/about'
  id: '__root__' | '/Login' | '/LokaleOversigt' | '/about'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  LokaleOversigtRoute: typeof LokaleOversigtRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  LokaleOversigtRoute: LokaleOversigtRoute,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/Login",
        "/LokaleOversigt",
        "/about"
      ]
    },
    "/Login": {
      "filePath": "Login.tsx"
    },
    "/LokaleOversigt": {
      "filePath": "LokaleOversigt.tsx"
    },
    "/about": {
      "filePath": "about.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
